language: node_js
node_js:
  - "10"
  - "lts/*"
os:
  - "linux"
  - "windows"
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/travis/.sonar/cache"
    - ".scannerwork"
    - "${TRAVIS_HOME}/.sonarscanner/"

#stages:
#  - lint
#  - test
#  - analyse
#  - deploy
#    if: branch = master

jobs:
  include:
#    - name: lint
#      node_js:
#        - "lts/*"
#        os:
#          - "linux"
#      script:
#        - npm run type-check
    - name: test
      script:
        - npm run test
        - npm run build
#    - name: analyse
#      node_js:
#        - "lts/*"
#        os:
#          - "linux"
#      script:
#        - npm run build
#        - npm run bundlesize
#        - npm run coverage
#        - sonar-scanner
    - stage: deploy
      node_js:
        - "lts/*"
      os:
        - "linux"
      script:
        - npm run build
      deploy:
        skip_cleanup: true
        provider: npm
        email: $DEPLOY_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true

git:
  depth: 99999

install:
  - npm ci

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN