language: node_js
node_js:
  - "lts/*"
os:
  - "linux"
  - "windows"
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/travis/.sonar/cache"
    - ".scannerwork"
    - "${TRAVIS_HOME}/.sonarscanner/"
    - "${TRAVIS_HOME}/.npm/"

stages:
  - compile
  - test
  - analyse
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script:
        - npm run type-check
      os:
        - "linux"
    - stage: test
      script:
        - npm run test
        - npm run build
    - stage: analyse
      os:
        - "linux"
      script:
        - npm run build
        - npm run bundlesize
        - npm run coverage
        - sonar-scanner
    - stage: deploy
      os:
        - "linux"
      script: skip
      deploy:
        skip_cleanup: true
        provider: npm
        email: $DEPLOY_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true

git:
  depth: 99999

install:
  - npm ci

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN